version: '2'
services:
  web:
    image: wordpress
    links:
      - db:mysql
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_USER: root
      WORDPRESS_DB_name: wordpress
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html
    db:
      image: mariadb
      environment:
        MYSQL_DATABASE: wordpress
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./db:/var/lib/mysql
      adminer:
        image: clue/adminer
        links:
          - db:mysql
        ports:
          - 8282:80
        environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: root
